fips = {
  "01": {"name":"Alabama",              "fp":"01",  "abbrev": "AL"},
  "02": {"name":"Alaska",               "fp":"02",  "abbrev": "AK"},
  "04": {"name":"Arizona",              "fp":"04",  "abbrev": "AZ"},
  "05": {"name":"Arkansas",             "fp":"05",  "abbrev": "AR"},
  "06": {"name":"California",           "fp":"06",  "abbrev": "CA"},
  "08": {"name":"Colorado",             "fp":"08",  "abbrev": "CO"},
  "09": {"name":"Connecticut",          "fp":"09",  "abbrev": "CT"},
  "10": {"name":"Delaware",             "fp":"10",  "abbrev": "DE"},
  "11": {"name":"District of Columbia", "fp":"11",  "abbrev": "DC"},
  "12": {"name":"Florida",              "fp":"12",  "abbrev": "FL"},
  "13": {"name":"Georgia",              "fp":"13",  "abbrev": "GA"},
  "15": {"name":"Hawaii",               "fp":"15",  "abbrev": "HI"},
  "16": {"name":"Idaho",                "fp":"16",  "abbrev": "ID"},
  "17": {"name":"Illinois",             "fp":"17",  "abbrev": "IL"},
  "18": {"name":"Indiana",              "fp":"18",  "abbrev": "IN"},
  "19": {"name":"Iowa",                 "fp":"19",  "abbrev": "IA"},
  "20": {"name":"Kansas",               "fp":"20",  "abbrev": "KS"},
  "21": {"name":"Kentucky",             "fp":"21",  "abbrev": "KY"},
  "22": {"name":"Louisiana",            "fp":"22",  "abbrev": "LA"},
  "23": {"name":"Maine",                "fp":"23",  "abbrev": "ME"},
  "24": {"name":"Maryland",             "fp":"24",  "abbrev": "MD"},
  "25": {"name":"Massachusetts",        "fp":"25",  "abbrev": "MA"},
  "26": {"name":"Michigan",             "fp":"26",  "abbrev": "MI"},
  "27": {"name":"Minnesota",            "fp":"27",  "abbrev": "MN"},
  "28": {"name":"Mississippi",          "fp":"28",  "abbrev": "MS"},
  "29": {"name":"Missouri",             "fp":"29",  "abbrev": "MO"},
  "30": {"name":"Montana",              "fp":"30",  "abbrev": "MT"},
  "31": {"name":"Nebraska",             "fp":"31",  "abbrev": "NE"},
  "32": {"name":"Nevada",               "fp":"32",  "abbrev": "NV"},
  "33": {"name":"New Hampshire",        "fp":"33",  "abbrev": "NH"},
  "34": {"name":"New Jersey",           "fp":"34",  "abbrev": "NJ"},
  "35": {"name":"New Mexico",           "fp":"35",  "abbrev": "NM"},
  "36": {"name":"New York",             "fp":"36",  "abbrev": "NY"},
  "37": {"name":"North Carolina",       "fp":"37",  "abbrev": "NC"},
  "38": {"name":"North Dakota",         "fp":"38",  "abbrev": "ND"},
  "39": {"name":"Ohio",                 "fp":"39",  "abbrev": "OH"},
  "40": {"name":"Oklahoma",             "fp":"40",  "abbrev": "OK"},
  "41": {"name":"Oregon",               "fp":"41",  "abbrev": "OR"},
  "42": {"name":"Pennsylvania",         "fp":"42",  "abbrev": "PA"},
  "44": {"name":"Rhode Island",         "fp":"44",  "abbrev": "RI"},
  "45": {"name":"South Carolina",       "fp":"45",  "abbrev": "SC"},
  "46": {"name":"South Dakota",         "fp":"46",  "abbrev": "SD"},
  "47": {"name":"Tennessee",            "fp":"47",  "abbrev": "TN"},
  "48": {"name":"Texas",                "fp":"48",  "abbrev": "TX"},
  "49": {"name":"Utah",                 "fp":"49",  "abbrev": "UT"},
  "50": {"name":"Vermont",              "fp":"50",  "abbrev": "VT"},
  "51": {"name":"Virginia",             "fp":"51",  "abbrev": "VA"},
  "53": {"name":"Washington",           "fp":"53",  "abbrev": "WA"},
  "54": {"name":"West Virginia",        "fp":"54",  "abbrev": "WV"},
  "55": {"name":"Wisconsin",            "fp":"55",  "abbrev": "WI"},
  "56": {"name":"Wyoming",              "fp":"56",  "abbrev": "WY"},
  "60": {"name":"American Samoa",                               "fp": "60",  "abbrev":"AS"},
  "64": {"name":"Federated States of Micronesia",               "fp": "64",  "abbrev":"FM"},
  "66": {"name":"Guam",                                         "fp": "66",  "abbrev":"GU"},
  "68": {"name":"Marshall Islands",                             "fp": "68",  "abbrev":"MH"},
  "69": {"name":"Commonwealth of the Northern Mariana Islands", "fp": "69",  "abbrev":"MP"},
  "70": {"name":"Palau",                                        "fp": "70",  "abbrev":"PW"},
  "72": {"name":"Puerto Rico",                                  "fp": "72",  "abbrev":"PR"},
  "74": {"name":"U.S. Minor Outlying Islands",                  "fp": "74",  "abbrev":"UM"},
  "78": {"name":"U.S. Virgin Islands",                          "fp": "78",  "abbrev":"VI"}
}